// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"github.com/hizzuu/plate-backend/ent"
)

type CreatePostPayload struct {
	Post *ent.Post `json:"post"`
}

type CreateUserPayload struct {
	User *ent.User `json:"user"`
}

type GetPostPayload struct {
	Post *ent.Post `json:"post"`
}

type GetUserPayload struct {
	User *ent.User `json:"user"`
}

type UpdateUserPayload struct {
	User *ent.User `json:"user"`
}
